### ISSUE TITLE
Jekyll::Converters::Markdown encountered an error

### ISSUE THREAD

**Issue by mosesontheweb** [jekyll/jekyll-commonmark#45]
Hi there,

I wasn't using Jekyll now for a while and today I wanted to restart some of my projects. Therefore I had to reinstall Ruby and Jekyll to my environment. Installation of my Gemfile works like expected, but whenever I try to run `bundle exec jekyll serve` I get following error:
```
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_faq/faq-allgemein.md':
                    uninitialized constant CommonMarker::Config::Parse Did you mean? OptParse
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
```
Trace output (cut not necessary lines before):
```
         ...
	 6: from /Users/thomas/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:106:in `block in convert'
	 5: from /Users/thomas/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/converters/markdown.rb:84:in `convert'
	 4: from /Users/thomas/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/converters/markdown.rb:15:in `setup'
	 3: from /Users/thomas/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/converters/markdown.rb:39:in `get_processor'
	 2: from /Users/thomas/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/converters/markdown.rb:98:in `custom_processor'
	 1: from /Users/thomas/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/converters/markdown.rb:98:in `new'
/Users/thomas/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/jekyll-commonmark-1.3.1/lib/jekyll-commonmark.rb:14:in `initialize': uninitialized constant CommonMarker::Config::Parse (NameError)
```
Jekyll is 4.2.0 (as you can see), Ruby is on version 2.7.4. I also tested it with Ruby 3.0.2 before and downgraded to 2.7.4 just to exlucde problems with a mjaor version hop. I run Ruby through `rbenv` (which didn't make a problem before). `jekyll-commonmark` is on version 1.3.1, `commonmarker` on 0.22.0. 

Any hints on this? Help appreciated, many thanks in advance.

Regards, Thomas

**Comment by ashmaroli** [comment]
Hi, you may point your Gemfile to the PR #44 to use the new version:

```ruby
gem 'jekyll-commonmark' , github: 'jekyll/jekyll-commonmark', ref: 'refs/pull/44/head'
```

**Comment by mosesontheweb** [comment]
Hi, thanks for the fast reply. That actually solved the issue, Jekyll now runs as expected.

Regards, Thomas
